import AllFiles from '@/components/AllFiles';
import './globals.css';

export const metadata = {
  title: 'dashboard',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <AllFiles children={children} />
      </body>
    </html>
  )
}